[project]
name = "design-patterns"
version = "0.1.0"
description = "Автоматизация сети ресторанов «Ромашка»"
readme = "README.md"
authors = [
    { name = "asutenshi", email = "zakan.6000@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[tool.uv]
package = false

[tool.pytest.ini_options]
pythonpath = ["."]

[dependency-groups]
dev = [
    "basedpyright>=1.40.1",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]

[tool.ruff]
src = ["Src"]

[tool.ruff.lint]
extend-select = ["N", "D101", "D102", "D103", "D105", "D107"]
ignore = [
    "N801",  # классы именуются в lowercase_separated_by_underscores
    "N999",  # каталоги именуются в CamelCase
]

[tool.basedpyright]
include = ["Src"]
extraPaths = ["Src"]
